version: '3.7'
services:
    app:
        container_name: dockerized-react-app
        build: .
        restart: always
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3000:3000'

