version: '3.7'
services:
    app:
        container_name: energy_dashboard
        build:
          context: .
          dockerfile: Dockerfile.prod
        restart: always
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '8800:80'

